---
# tasks file for cdh-master-installation
- name: Installing maria-db-server
  yum:
    name: mariadb-server
    state: latest

- name: Start and Enable maria-db
  systemd:
    state: started
    enabled: yes
    name: mariadb

- name: Copy file with owner and permissions - MySQL scripts
  copy:
    src: ./mysql.sh
    dest: /tmp/mysql.sh
    owner: luisfilho
    group: luisfilho
    mode: '0755'

- name: Execute MySQL script
  command: bash /tmp/mysql.sh
  become: yes

- name: Installing cloudera-manager-server
  yum:
    name: cloudera-manager-server
    state: present

- name: SCM Prepare Database
  command: bash /opt/cloudera/cm/schema/scm_prepare_database.sh mysql scm scm scm
  become: yes

- name: Start Cloudera Manager Server
  systemd:
    name: cloudera-scm-server
    state: started
    enabled: yes

- name: Checking Cloudera Manager API
  uri:
    url: "http://{{ hostvars['cloudera'].ansible_default_ipv4.address }}:7180/api/v12/hosts"
    user: admin
    password: admin
    method: GET
  register: _result
  until: _result.status == 200
  retries: 720
  delay: 5

- name: Copy python script template
  template:
    src: ./set_cloudera_host.py.j2 
    dest: /tmp/set_cloudera_host.py
    owner: luisfilho
    group: luisfilho
    mode: '0755'

- name: Create environment variable
  command: python3 /tmp/set_cloudera_host.py
  register: idNode

- name: Template a file to /etc/files.conf
  template:
    src: ./mgmt-template.json.j2
    dest: "{{ tmp_dir }}/mgmt-template.json"
    owner: luisfilho
    group: luisfilho
    mode: '0644'
  vars:
    masterid: "{{ idNode.stdout }}"

- name: Content of JSON
  command: cat {{ tmp_dir }}/mgmt-template.json
  register: jsonContent

- name: Use Trial License
  uri:
    url: "http://{{ hostvars['cloudera'].ansible_default_ipv4.address }}:7180/api/v12/cm/trial/begin"
    user: admin
    password: admin
    method: POST
    status_code: 204

- name: Create MGMT
  uri:
    url: "http://{{ hostvars['cloudera'].ansible_default_ipv4.address }}:7180/api/v12/cm/service"
    body: "{{ content }}"
    user: admin
    password: admin
    method: PUT
    body_format: json
  vars:
    content: "{{ jsonContent.stdout }}"

- name: Start MGMT
  uri:
    url: "http://{{ hostvars['cloudera'].ansible_default_ipv4.address }}:7180/api/v12/cm/service/commands/start"
    user: admin
    password: admin
    method: POST
  register: _result2
  until: _result2.status == 200
  retries: 720
  delay: 5

- name: Cloudera template to /tmp/cm-template.json
  template:
    src: ./cm-template.json.j2
    dest: "{{ tmp_dir }}/cm-template.json"
    owner: luisfilho
    group: luisfilho
    mode: '0644'

- name: Content of JSON
  command: cat {{ tmp_dir }}/cm-template.json
  register: clouderaTemplateContent

- name: Using Cluster Deployment
  uri:
    url: "http://{{ hostvars['cloudera'].ansible_default_ipv4.address }}:7180/api/v12/cm/importClusterTemplate?addRepositories=true"
    body: "{{ clouderaTemplateContent.stdout }}"
    user: admin
    password: admin
    method: POST
    body_format: json
  register: _result2
  until: _result2.status == 200
  retries: 720 
  delay: 5
